#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 23 23:19:38 2020

@author: akashkumar
"""

from collections import defaultdict

graph = defaultdict(list)

q = int(input())
n, m, cl, cr = int(input().split())


a = [3,2,2,4,5,3,32,2,4]

print(a[:len(a)-1])

def fun(a):
    n = len(a)
    if n>=1:
        print(a[n-1], end = '')
        fun(a[:n-1])



fun(['a','k','a','s','h'])









































                                                                                                                                                                                                                                                                                                                                                




























