#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 28 16:19:41 2020

@author: akashkumar
"""

(_, A) = (int(input()),set(map(int, input().split())))

B = int(input())

for i in range(B):
    (command, new) = (input.split()[0], set(map(int,input().split())))
    
    
    
    
    
    